### ISSUE TITLE
Error when output_folder does not exist

### ISSUE THREAD

**Issue by LudoBar** [Ikomia-hub/dataset_coco#1]
Dataset loader failed to run if parameter "output_folder" is set with a non existing folder.

Expected behavior: folder creation if not exists.

```
wf = workflow.Workflow("New")

image_folder = "datasets/wgisd/data"
json_path = "datasets/wgisd/coco_annotations/test_polygons_instances.json"
out_folder = "datasets/wgisd/semantic" # not existing

coco_wgisd = wf.add_task(ik.dataset_coco(task="semantic_segmentation",
                                             image_folder=image_folder,
                                             json_path=json_path,
                                             output_folder=out_folder))
wf.run()
```

**Comment by allankouidri** [comment]
Hi, 

The code has been edited to make a directory if:
- the folder doesn't exist
- no path has been set, then a folder will be created in the dataset_coco folder

The edit was pushed in the api_0.9.0 branch, it will be merged to main in the near future. 

Thank you.
